### ISSUE TITLE
关于Licene的问题

### ISSUE THREAD

**Issue by donglua** [weui/weui-design#3]
请问，如果我在Github上的app使用了本项目的一些控件，我还能否使用开源许可协议，如GPL、LGPL、Apache、BSD、MIT等。

**Comment by progrape** [comment]
@donglua 开发者可以使用 weui-sketch 进行创作，衍生出自己的作品，我们鼓励开源分享出来，开发者可以自行选择开源协议~

**Comment by donglua** [comment]
ok, thx
