### ISSUE TITLE
说说怎样用不侵犯权益？

### ISSUE THREAD

**Issue by calidion** [weui/weui-design#4]
如果使用了，如何避免被腾讯告上南山法院？

**Comment by calidion** [comment]
weui是MIT表示放弃所有的权力。
而这里又在声明权力。
非常矛盾。

**Comment by progrape** [comment]
首先，MIT 协议并非你说的“放弃所有权力”，MIT协议表明原作者保留对作品的版权，你可以自由地使用，但需要遵守：

> The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

其次，以 MIT 协议开源的是 WeUI 的代码，而 `weui-sketch` 是 WeUI 的设计稿，没有什么矛盾。我们保留 `weui-sketch` 的版权，同样也赋予开发者、设计师非常大的使用自由，允许、鼓励使用 `weui-sketch` 加工演绎出自己的作品。

**Comment by calidion** [comment]
```
我们禁止

未经允许直接利用 WeUI-Sketch 作品开展牟利行为，包括但不限于打包售卖、另行建立镜像收取费用、有偿下载、积分下载等行为
```

据我所知这个东西是无法通过MIT禁止的。
MIT只是保留了原作者的版权声明，但是允许任何人以任何方式使用作品。
所以牟利，打包售卖，建立镜收费都不是MIT所禁止的。

所以如何做到基于MIT使用weui，而不会被这里的版权声明所限制？

**Comment by calidion** [comment]
如果我的理解没有错误。
根据weui-sketch的声明
weui的MIT协议已经违反了weui-sketch的声明。
所以weui的MIT协议的无效的。

**Comment by progrape** [comment]
weui-sketch 并非简单的 MIT 协议，而是一个声明：
允许演绎自己的作品，演绎的作品鼓励开源；
禁止直接售卖 sketch 文件。

weui 如何违反 weui-sketch 的声明，导致 weui 的 MIT 协议无效？

**Comment by calidion** [comment]
现在的问题是什么是“直接利用”？
如果任何对这个作品的转化都不属于直接利用。
是不是表明，只要将文化的格式转化后就不侵权了？
如何介定直接还是间接？
weui是间接还是直接？
如果weui是间接的，那么所有的人只要变换一下就可以复制，发行。
似乎又跟你的声明所表达的意义相违背。

**Comment by progrape** [comment]
我们期望的“转化”、“演绎”，是指使用 weui-sketch 的控件，经过组合、适当的修改，来做出一个 Web App 的原型设计或者视觉设计。

拟定这个声明的本意，一方面是声明版权归属，另一方面是不希望看到我们设计师的劳动成果，直接被他人拿去售卖牟利。至于如何界定直接还是间接，我们确实无法给出一个量化的标准，但可以通过举例来表达我们的意思。我们想到的场景可能直接牟利的场景有，直接卖 sketch 文件、建立镜像进行积分下载或付费下载等。

当然了，任何规则，你要去深究的话都总可以钻空子的。就算是明文禁止，你也无法阻止会有人这样做，对吧？

**Comment by calidion** [comment]
如果我理解的没错，你们对开源还是存在着误解。
开源协议的本意是自由的获取源代码的权力，但是并没有限制通过源码挣钱的权力。
因此不惜放弃对源码的控制权，允许人们修改源码后开源。
对于源码的控制权的不同，分成不同的开源协议。包括GPL，MIT等。
GPL会要求修改后的软件分发时必须同时开源，而MIT则是可以闭源的。
但是都不会限制别人通过软件挣钱。即使是GPL的软件，也是鼓励通过买光盘挣钱的。
只是买光盘没有下载来的方便，大部分人不会花这个钱。
所以我理解你的担心，但是同时我认为你误会了开源的意义。

开源很多时候就是放弃绝对的商业控制权。

**Comment by progrape** [comment]
开源的意义，这种问题，我相信不同人，有不同的理解，何来误解？

**Comment by calidion** [comment]
对于开源有不同的看法我觉得没有问题，但是不同的看法是通过不同的协议体现的。
所以对于不同的协议，他们的意义是明确的。
如果一个协议能让不同的人有不同的理解，那么制订这个协议就没有意义了。
协议的作用就是消除歧义。

所以对于确定的协议并不存在不同的理解之说。
