### ISSUE TITLE
Sketch 源文件怎样输出字体？

### ISSUE THREAD

**Issue by philwu** [weui/weui-design#5]
小白问个问题，我在sketch里加入了几个图标，想把它输出成图标字体，最好就像weui.css里的那样base64的，我该怎么做呀？

这个问题跟项目本身无关，如有打扰，抱歉了。

**Comment by progrape** [comment]
@philwu 先用 sketch 输出 svg 文件，然后使用工具把 svg 转成字体文件，在线工具可以使用 http://fontello.com/ ，命令行工具可以使用 https://github.com/nfroidure/gulp-iconfont
